package:
    type:           library
    name:           php-collection
    namespace:      hiqdev\php\collection
    headline:       PHP Collection
    title:          Collection library for PHP
    keywords:       collection, library, php
    year:           2015

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-hiqdev: "*"
